// Code generated by tygo. DO NOT EDIT.

//////////
// source: dispatch.go

export interface DispatchRequest {
  namespace: string;
}
export interface DispatchResponse {
  dispatch_id: string;
  namespace: string;
  queued_count: number /* int */;
  status: string;
}

//////////
// source: errors.go

export interface ErrorResponse {
  error: string;
}

//////////
// source: namespace.go

export interface Namespace {
  name: string;
  description?: string;
  provider?: ProviderOverride;
  stats?: NamespaceStats;
  created_at: string;
  updated_at: string;
}
export interface ProviderOverride {
  api_endpoint?: string;
  api_key?: string;
  model?: string;
  headers?: { [key: string]: string};
}
export interface NamespaceStats {
  total_requests: number /* int */;
  queued: number /* int */;
  processing: number /* int */;
  completed: number /* int */;
  failed: number /* int */;
}
export interface CreateNamespaceRequest {
  name: string;
  description?: string;
  provider?: ProviderOverride;
}
export interface UpdateNamespaceRequest {
  description?: string;
  provider?: ProviderOverride;
}
export interface DeleteNamespaceResponse {
  message: string;
}

//////////
// source: request.go

export type RequestStatus = string;
export const StatusQueued: RequestStatus = "queued";
export const StatusProcessing: RequestStatus = "processing";
export const StatusCompleted: RequestStatus = "completed";
export const StatusFailed: RequestStatus = "failed";
export interface Request {
  id: string;
  namespace: string;
  status: RequestStatus;
  response?: { [key: string]: any};
  error?: string;
  created_at: string;
  dispatched_at?: string;
  completed_at?: string;
}
export interface QueuedRequestResponse {
  id: string;
  namespace: string;
  status: RequestStatus;
  created_at: string;
}
export interface ListRequestsResponse {
  requests: Request[];
  total: number /* int */;
  limit: number /* int */;
  next_cursor?: string;
}
