// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Namespace struct {
	Name             string         `json:"name"`
	Description      string         `json:"description"`
	ProviderEndpoint sql.NullString `json:"provider_endpoint"`
	ProviderApiKey   sql.NullString `json:"provider_api_key"`
	ProviderModel    sql.NullString `json:"provider_model"`
	ProviderHeaders  sql.NullString `json:"provider_headers"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

type Request struct {
	ID                 string         `json:"id"`
	Namespace          string         `json:"namespace"`
	Status             string         `json:"status"`
	RequestPayload     string         `json:"request_payload"`
	PassthroughHeaders sql.NullString `json:"passthrough_headers"`
	HeaderEndpoint     sql.NullString `json:"header_endpoint"`
	HeaderApiKey       sql.NullString `json:"header_api_key"`
	ResponsePayload    sql.NullString `json:"response_payload"`
	Error              sql.NullString `json:"error"`
	CreatedAt          int64          `json:"created_at"`
	DispatchedAt       sql.NullInt64  `json:"dispatched_at"`
	CompletedAt        sql.NullInt64  `json:"completed_at"`
}
