// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountRequestsByNamespace(ctx context.Context, namespace string) (int64, error)
	CountRequestsByNamespaceAndStatus(ctx context.Context, arg CountRequestsByNamespaceAndStatusParams) (int64, error)
	CreateNamespace(ctx context.Context, arg CreateNamespaceParams) error
	CreateRequest(ctx context.Context, arg CreateRequestParams) error
	DeleteNamespace(ctx context.Context, name string) error
	DeleteRequestsByNamespace(ctx context.Context, namespace string) (int64, error)
	GetNamespace(ctx context.Context, name string) (Namespace, error)
	GetNamespaceStats(ctx context.Context, namespace string) (GetNamespaceStatsRow, error)
	GetQueuedRequestsByNamespace(ctx context.Context, namespace string) ([]Request, error)
	GetRequest(ctx context.Context, id string) (Request, error)
	ListNamespaces(ctx context.Context) ([]Namespace, error)
	ListRequestsByNamespace(ctx context.Context, arg ListRequestsByNamespaceParams) ([]Request, error)
	ListRequestsByNamespaceAndStatus(ctx context.Context, arg ListRequestsByNamespaceAndStatusParams) ([]Request, error)
	ListRequestsByNamespaceAndStatusWithCursor(ctx context.Context, arg ListRequestsByNamespaceAndStatusWithCursorParams) ([]Request, error)
	ListRequestsByNamespaceWithCursor(ctx context.Context, arg ListRequestsByNamespaceWithCursorParams) ([]Request, error)
	UpdateNamespace(ctx context.Context, arg UpdateNamespaceParams) error
	UpdateRequestError(ctx context.Context, arg UpdateRequestErrorParams) error
	UpdateRequestResponse(ctx context.Context, arg UpdateRequestResponseParams) error
	UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) error
}

var _ Querier = (*Queries)(nil)
