// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countRequestsByNamespace = `-- name: CountRequestsByNamespace :one
SELECT COUNT(*) as total FROM requests WHERE namespace = ?
`

func (q *Queries) CountRequestsByNamespace(ctx context.Context, namespace string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRequestsByNamespace, namespace)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countRequestsByNamespaceAndStatus = `-- name: CountRequestsByNamespaceAndStatus :one
SELECT COUNT(*) as total FROM requests WHERE namespace = ? AND status = ?
`

type CountRequestsByNamespaceAndStatusParams struct {
	Namespace string `json:"namespace"`
	Status    string `json:"status"`
}

func (q *Queries) CountRequestsByNamespaceAndStatus(ctx context.Context, arg CountRequestsByNamespaceAndStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRequestsByNamespaceAndStatus, arg.Namespace, arg.Status)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createNamespace = `-- name: CreateNamespace :exec
INSERT INTO namespaces (name, description, provider_endpoint, provider_api_key, provider_model, provider_headers, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateNamespaceParams struct {
	Name             string         `json:"name"`
	Description      string         `json:"description"`
	ProviderEndpoint sql.NullString `json:"provider_endpoint"`
	ProviderApiKey   sql.NullString `json:"provider_api_key"`
	ProviderModel    sql.NullString `json:"provider_model"`
	ProviderHeaders  sql.NullString `json:"provider_headers"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) CreateNamespace(ctx context.Context, arg CreateNamespaceParams) error {
	_, err := q.db.ExecContext(ctx, createNamespace,
		arg.Name,
		arg.Description,
		arg.ProviderEndpoint,
		arg.ProviderApiKey,
		arg.ProviderModel,
		arg.ProviderHeaders,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRequest = `-- name: CreateRequest :exec
INSERT INTO requests (id, namespace, status, request_payload, passthrough_headers, header_endpoint, header_api_key, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRequestParams struct {
	ID                 string         `json:"id"`
	Namespace          string         `json:"namespace"`
	Status             string         `json:"status"`
	RequestPayload     string         `json:"request_payload"`
	PassthroughHeaders sql.NullString `json:"passthrough_headers"`
	HeaderEndpoint     sql.NullString `json:"header_endpoint"`
	HeaderApiKey       sql.NullString `json:"header_api_key"`
	CreatedAt          int64          `json:"created_at"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) error {
	_, err := q.db.ExecContext(ctx, createRequest,
		arg.ID,
		arg.Namespace,
		arg.Status,
		arg.RequestPayload,
		arg.PassthroughHeaders,
		arg.HeaderEndpoint,
		arg.HeaderApiKey,
		arg.CreatedAt,
	)
	return err
}

const deleteNamespace = `-- name: DeleteNamespace :exec
DELETE FROM namespaces WHERE name = ?
`

func (q *Queries) DeleteNamespace(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteNamespace, name)
	return err
}

const deleteRequestsByNamespace = `-- name: DeleteRequestsByNamespace :execrows
DELETE FROM requests WHERE namespace = ?
`

func (q *Queries) DeleteRequestsByNamespace(ctx context.Context, namespace string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRequestsByNamespace, namespace)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNamespace = `-- name: GetNamespace :one
SELECT name, description, provider_endpoint, provider_api_key, provider_model, provider_headers, created_at, updated_at
FROM namespaces
WHERE name = ?
`

func (q *Queries) GetNamespace(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, getNamespace, name)
	var i Namespace
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.ProviderEndpoint,
		&i.ProviderApiKey,
		&i.ProviderModel,
		&i.ProviderHeaders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNamespaceStats = `-- name: GetNamespaceStats :one
SELECT
    COUNT(*) as total_requests,
    SUM(CASE WHEN status = 'queued' THEN 1 ELSE 0 END) as queued,
    SUM(CASE WHEN status = 'processing' THEN 1 ELSE 0 END) as processing,
    SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) as completed,
    SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END) as failed
FROM requests
WHERE namespace = ?
`

type GetNamespaceStatsRow struct {
	TotalRequests int64           `json:"total_requests"`
	Queued        sql.NullFloat64 `json:"queued"`
	Processing    sql.NullFloat64 `json:"processing"`
	Completed     sql.NullFloat64 `json:"completed"`
	Failed        sql.NullFloat64 `json:"failed"`
}

func (q *Queries) GetNamespaceStats(ctx context.Context, namespace string) (GetNamespaceStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceStats, namespace)
	var i GetNamespaceStatsRow
	err := row.Scan(
		&i.TotalRequests,
		&i.Queued,
		&i.Processing,
		&i.Completed,
		&i.Failed,
	)
	return i, err
}

const getQueuedRequestsByNamespace = `-- name: GetQueuedRequestsByNamespace :many
SELECT id, namespace, status, request_payload, passthrough_headers, header_endpoint, header_api_key, response_payload, error, created_at, dispatched_at, completed_at
FROM requests
WHERE namespace = ? AND status = 'queued'
ORDER BY created_at ASC
`

func (q *Queries) GetQueuedRequestsByNamespace(ctx context.Context, namespace string) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, getQueuedRequestsByNamespace, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.Status,
			&i.RequestPayload,
			&i.PassthroughHeaders,
			&i.HeaderEndpoint,
			&i.HeaderApiKey,
			&i.ResponsePayload,
			&i.Error,
			&i.CreatedAt,
			&i.DispatchedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequest = `-- name: GetRequest :one
SELECT id, namespace, status, request_payload, passthrough_headers, header_endpoint, header_api_key, response_payload, error, created_at, dispatched_at, completed_at
FROM requests
WHERE id = ?
`

func (q *Queries) GetRequest(ctx context.Context, id string) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.Status,
		&i.RequestPayload,
		&i.PassthroughHeaders,
		&i.HeaderEndpoint,
		&i.HeaderApiKey,
		&i.ResponsePayload,
		&i.Error,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listNamespaces = `-- name: ListNamespaces :many
SELECT name, description, provider_endpoint, provider_api_key, provider_model, provider_headers, created_at, updated_at
FROM namespaces
ORDER BY name
`

func (q *Queries) ListNamespaces(ctx context.Context) ([]Namespace, error) {
	rows, err := q.db.QueryContext(ctx, listNamespaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Namespace
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.ProviderEndpoint,
			&i.ProviderApiKey,
			&i.ProviderModel,
			&i.ProviderHeaders,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByNamespace = `-- name: ListRequestsByNamespace :many
SELECT id, namespace, status, request_payload, passthrough_headers, header_endpoint, header_api_key, response_payload, error, created_at, dispatched_at, completed_at
FROM requests
WHERE namespace = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListRequestsByNamespaceParams struct {
	Namespace string `json:"namespace"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListRequestsByNamespace(ctx context.Context, arg ListRequestsByNamespaceParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsByNamespace, arg.Namespace, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.Status,
			&i.RequestPayload,
			&i.PassthroughHeaders,
			&i.HeaderEndpoint,
			&i.HeaderApiKey,
			&i.ResponsePayload,
			&i.Error,
			&i.CreatedAt,
			&i.DispatchedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByNamespaceAndStatus = `-- name: ListRequestsByNamespaceAndStatus :many
SELECT id, namespace, status, request_payload, passthrough_headers, header_endpoint, header_api_key, response_payload, error, created_at, dispatched_at, completed_at
FROM requests
WHERE namespace = ? AND status = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListRequestsByNamespaceAndStatusParams struct {
	Namespace string `json:"namespace"`
	Status    string `json:"status"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListRequestsByNamespaceAndStatus(ctx context.Context, arg ListRequestsByNamespaceAndStatusParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsByNamespaceAndStatus, arg.Namespace, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.Status,
			&i.RequestPayload,
			&i.PassthroughHeaders,
			&i.HeaderEndpoint,
			&i.HeaderApiKey,
			&i.ResponsePayload,
			&i.Error,
			&i.CreatedAt,
			&i.DispatchedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByNamespaceAndStatusWithCursor = `-- name: ListRequestsByNamespaceAndStatusWithCursor :many
SELECT id, namespace, status, request_payload, passthrough_headers, header_endpoint, header_api_key, response_payload, error, created_at, dispatched_at, completed_at
FROM requests
WHERE namespace = ? AND status = ? AND created_at < ?
ORDER BY created_at DESC
LIMIT ?
`

type ListRequestsByNamespaceAndStatusWithCursorParams struct {
	Namespace string `json:"namespace"`
	Status    string `json:"status"`
	CreatedAt int64  `json:"created_at"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListRequestsByNamespaceAndStatusWithCursor(ctx context.Context, arg ListRequestsByNamespaceAndStatusWithCursorParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsByNamespaceAndStatusWithCursor,
		arg.Namespace,
		arg.Status,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.Status,
			&i.RequestPayload,
			&i.PassthroughHeaders,
			&i.HeaderEndpoint,
			&i.HeaderApiKey,
			&i.ResponsePayload,
			&i.Error,
			&i.CreatedAt,
			&i.DispatchedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByNamespaceWithCursor = `-- name: ListRequestsByNamespaceWithCursor :many
SELECT id, namespace, status, request_payload, passthrough_headers, header_endpoint, header_api_key, response_payload, error, created_at, dispatched_at, completed_at
FROM requests
WHERE namespace = ? AND created_at < ?
ORDER BY created_at DESC
LIMIT ?
`

type ListRequestsByNamespaceWithCursorParams struct {
	Namespace string `json:"namespace"`
	CreatedAt int64  `json:"created_at"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListRequestsByNamespaceWithCursor(ctx context.Context, arg ListRequestsByNamespaceWithCursorParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsByNamespaceWithCursor, arg.Namespace, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.Status,
			&i.RequestPayload,
			&i.PassthroughHeaders,
			&i.HeaderEndpoint,
			&i.HeaderApiKey,
			&i.ResponsePayload,
			&i.Error,
			&i.CreatedAt,
			&i.DispatchedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNamespace = `-- name: UpdateNamespace :exec
UPDATE namespaces
SET description = ?, provider_endpoint = ?, provider_api_key = ?, provider_model = ?, provider_headers = ?, updated_at = ?
WHERE name = ?
`

type UpdateNamespaceParams struct {
	Description      string         `json:"description"`
	ProviderEndpoint sql.NullString `json:"provider_endpoint"`
	ProviderApiKey   sql.NullString `json:"provider_api_key"`
	ProviderModel    sql.NullString `json:"provider_model"`
	ProviderHeaders  sql.NullString `json:"provider_headers"`
	UpdatedAt        int64          `json:"updated_at"`
	Name             string         `json:"name"`
}

func (q *Queries) UpdateNamespace(ctx context.Context, arg UpdateNamespaceParams) error {
	_, err := q.db.ExecContext(ctx, updateNamespace,
		arg.Description,
		arg.ProviderEndpoint,
		arg.ProviderApiKey,
		arg.ProviderModel,
		arg.ProviderHeaders,
		arg.UpdatedAt,
		arg.Name,
	)
	return err
}

const updateRequestError = `-- name: UpdateRequestError :exec
UPDATE requests SET status = 'failed', error = ?, completed_at = ? WHERE id = ?
`

type UpdateRequestErrorParams struct {
	Error       sql.NullString `json:"error"`
	CompletedAt sql.NullInt64  `json:"completed_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateRequestError(ctx context.Context, arg UpdateRequestErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateRequestError, arg.Error, arg.CompletedAt, arg.ID)
	return err
}

const updateRequestResponse = `-- name: UpdateRequestResponse :exec
UPDATE requests SET status = 'completed', response_payload = ?, completed_at = ? WHERE id = ?
`

type UpdateRequestResponseParams struct {
	ResponsePayload sql.NullString `json:"response_payload"`
	CompletedAt     sql.NullInt64  `json:"completed_at"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateRequestResponse(ctx context.Context, arg UpdateRequestResponseParams) error {
	_, err := q.db.ExecContext(ctx, updateRequestResponse, arg.ResponsePayload, arg.CompletedAt, arg.ID)
	return err
}

const updateRequestStatus = `-- name: UpdateRequestStatus :exec
UPDATE requests SET status = ?, dispatched_at = ? WHERE id = ?
`

type UpdateRequestStatusParams struct {
	Status       string        `json:"status"`
	DispatchedAt sql.NullInt64 `json:"dispatched_at"`
	ID           string        `json:"id"`
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRequestStatus, arg.Status, arg.DispatchedAt, arg.ID)
	return err
}
